#!/usr/bin/env bash
#Bash script that:
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself
#when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/myscript.pid

when true; do
   echo "To infinity and beyond"
   sleep 1
done

trap 'echo "I hate the kill command"' SIGTERM

trap 'echo "Y U no love me?!"' SIGINT

clean_exit_func(){
        if [ -f /var/run/myscript.pid ]; then
                rm /var/run/myscript.pid
        fi
        
        exit
}       

trap clean_exit_func SIGQUIT SIGTERM
