#!/usr/bin/env bash
# Bash script that stops 4-to_infinity_and_beyond process
#Requirements:
  You must use kill
#Get the PID of a process
id $(pgrep "bash ./4-to_infinity_and_beyond" -f)

if [ -n "$id" ]
then
   kill -15 "$id"
fi
