#!/usr/bin/env bash
#Printing Best School nine times then print Hi on newline
#Required to use while and if loops

count=0

while [ $count -lt 10 ]
do
    
    if [ $count -eq 9 ]
    then
         echo "Hi"
    fi
    echo "Best School"
done
